gristmill/gristmill/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import TemplateView, ListView, DetailView
#from django.views.generic.date_based import object_detail, archive_day, archive_month, archive_year, archive_index
from django.views.generic.dates import ArchiveIndexView, YearArchiveView
from galleria.models import Tag, Image
from galleria.views import gal_by_tag, image_detail 
from gristmill.views import HomeStaticTemplateView, about_pages
from daily_grist.views import EntryListView, EntryDetailView, BlogArchiveIndexView
from testimonials.views import QuotationListView
from testimonials.views import TestimonialArchiveIndexView
from homepage.views import HomepageView
from daily_grist.models import Entry
from testimonials.models import Quotation, Customer
from homepage.models import PageIntro, TeaserImage, Teaser
from contact.forms import ContactForm
from contact.views import contact

# from taggit.models import Tag, TaggedItem
import datetime      

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
# Come back to Home and About sections when galleria is done
# home
    (r'^$', HomepageView.as_view()),
#
# Class-based Generic Views for galleria    
	(r'^tags/$', ListView.as_view(model=Tag, context_object_name="tag_list", template_name="galleria/tag_list.html",)),
#
# My own view functions for galleria
#    (r'^gallery/(all)/$', gal_all),														
    #(r'^gallery/([\w-]+)/(?P<image_id>\d+)/$', image_detail),
    (r'^gallery/(\d+)/$', image_detail),
    (r'^gallery/([\w-]+)/$', gal_by_tag),
#
# Class-based generic views for daily-grist
    (r'^daily-grist/$', EntryListView.as_view()),
    (r'^daily-grist/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/(?P<slug>[\w-]+)/$', EntryDetailView.as_view(),),
    (r'^daily-grist/archive/$', BlogArchiveIndexView.as_view(),),
    #(r'^daily-grist/archive/(?P<year>\d{4})/$', BlogYearArchiveView.as_view(),),
#
# Class-based generic views for testimonials
    (r'^testimonials/$', QuotationListView.as_view()),
	(r'^testimonials/archive/$', TestimonialArchiveIndexView.as_view()),
#
# Forms
    (r'^contact/$', contact),
    (r'^thanks/$', direct_to_template, {'template': 'thanks.html'}),

#
# All content subsections are flatpages
    #(r'^about/$', direct_to_template, {'template': 'about/about.html'}),
    #(r'^about/(\w+)/$', about_pages),
#
# Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)    
#
# Will need to turn this off in production
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

gristmill/daily_grist/models.py
from django.db import models
#from django.contrib.syndication.views.Feed import Feed
#from django.utils import feedgenerator
from django.contrib.sitemaps import Sitemap
import markdown
from taggit.managers import TaggableManager
from galleria.models import Image

import datetime

# Create your models here.
class Entry(models.Model):
	title = models.CharField(max_length=255)
	#Optional lead_image can be chosen from the photo gallery.
	lead_image = models.ForeignKey(Image, blank=True, null=True, on_delete=models.SET_NULL)
	slug = models.SlugField(unique_for_date='pub_date', help_text='Automatically created from the title.')
	body_html = models.TextField(blank=True)
	body_markdown = models.TextField(help_text='Use Markdown syntax')
	pub_date = models.DateTimeField('date published')
	mod_date = models.DateTimeField(auto_now=True) #defaults to now
	last_accessed = models.DateTimeField(auto_now=True) #defaults to now for a last accessed timestamp
	enable_comments = models.BooleanField(default=True)
	
	PUB_STATUS = (
	   (0, 'Draft'),
	   (1, 'Published'),
	)
	status = models.IntegerField(choices=PUB_STATUS, default=0)
	
	tags = TaggableManager()
	
	class Meta:
		ordering = ('-pub_date',)
		get_latest_by = ('pub_date')
		verbose_name_plural = 'entries'
   	
	def __unicode__(self):
	    return u'%s' %(self.title)
	
	def get_absolute_url(self):
		return "/daily-grist/%s/%s/" %(self.pub_date.strftime("%Y/%b/%d").lower(), self.slug)
		     
	def save(self):
	    self.body_html = markdown.markdown(self.body_markdown, safe_mode=False)
	    super(Entry, self).save()
	
	def get_previous_published(self):
		return self.get_previous_by_pub_date(status__exact=1)
	
	def get_next_published(self):
		return self.get_next_by_pub_date(status__exact=1)

# taggit is not working	
#	def get_tags(self):
#		return Tag.objects.get_for_object(self)
		

gristmill/galleria/models.py
from django.db import models
from django.db.models import permalink

class Tag(models.Model):
	name = models.CharField('tag name', help_text='maximum length 100', max_length=100, unique=True)
	slug = models.SlugField(max_length=100, unique=True, help_text='Suggested value automatically created from name. Must be unique.') 
	def __unicode__(self):
		return u"%s" % (self.name)

	class Meta:
		ordering = ['name']
    
	"""
	Permanent url to a tag's slug. Can be used in templates."""
	@permalink
	def get_absolute_url(self):
		return ('galleria.views.gal_by_tag', [str(self.slug)])
   	
class Image(models.Model):
    filename = models.ImageField(help_text='Width and height no larger than 700px at 72dpi. Images are uploaded to the photos folder. Duplicates will have a an underscore and number added to filename (eg. image_2.jpg)', upload_to='photos/')
    caption = models.CharField(help_text='Short catchy title for the image (maximum length 100 characters)', max_length=100)
    description = models.TextField(help_text='Longer description of the image. Try to build some interest here, keep it to under 300 characters.', max_length=300, null=True, blank=True)
    pub_date = models.DateTimeField('date published')
    tags = models.ManyToManyField(Tag)
#	enable_comments = 
    def __unicode__(self):
		return u"%s (%s)" % (self.caption, u", ".join([tag.name
		                                            for tag in self.tags.all()]))
    class Meta:
		ordering = ['-pub_date']		

    """
    Permanent url to image detail view to use in templates."""
    @permalink
    def get_absolute_url(self):
	    return ('galleria.views.image_detail', [str(self.id)])
	
    """
	Wrapper function to use in template to get the path to the image file. """
    def get_img_url(self):
        return "/media/%s" %(self.filename)

gristmill/templates/includes/contact_menu.html
<ul id="contactMenu">
    <li><a href="#">What we do</a></li>
    <li><a href="/about/">Who we are</a></li>
    <li><a href="#">Contact us</a></li>
    <li><a href="#">Getting here</a></li>
</ul>

gristmill/templates/includes/features.html
<ul id="features">
  <li><a href="/gallery/all/"><img src="/media/features/cupcakeBearsBlue.png" alt="Cup cake bears (blue)"></a></li>
</ul>

gristmill/templates/includes/main_nav.html
<ul>
	<li><a href="/wedding-cakes/">Wedding Cakes</a></li>
	<li><a href="/cakes/">Custom Cakes</a></li>
	<li><a href="/catering/">Light Catering</a></li>
	<li><a href="/daily-grist/">Daily Grist Blog</a></li>
	<li><a href="/gallery/all/">All Photo Galleries</a></li>
</ul>

gristmill/templates/includes/promo.html
<section id="promo">
  <div class="grid_4">
    <a class="hotBox" href="/bakery/">
      <h2>Bakery</h2>
		   <img src="/media/img/file.jpg" alt="alt">
		<p>We've got all your baked good needs. From cake to cookies, pastries to your daily bread.</p>
    </a>
  </div>
  <!-- end .grid_4 -->
  <div class="grid_4">
    <a class="hotBox" href="/deli/">
      <h2>Deli</h2>
		   <img src="/media/img/file.jpg" alt="alt">
		<p>We've got more than a fabulous sandwich bar. You'll find your favourite meats and cheeses, fresh home-made soups and salads and then there is the grill...</p>
    </a>
  </div>
  <!-- end .grid_4 -->
  <div class="grid_4 omega">
    <a class="hotBox" href="/cafe/">
      <h2>Caf&eacute;</h2>
		   <img src="/media/img/file.jpg" alt="alt">
		<p>Espresso just how you like it, an array of fresh brewed coffee, an assortment of tea are staples in not drinks, and we've got milk shakes, smoothies and home-made iced tea, too...</p>
    </a>
  </div>
  <!-- end .grid_4 -->
  <div class="clear"></div> 
</section>

gristmill/templates/includes/quick_menu.html
<h3>Quick links</h3>
	<ul id="quickMenu" class="menu">
		<li id="giftcard"><a href="#">Recharge your giftcard</a></li>
		<li id="signup"><a href="#">Signup</a> for our newsletter!</li>
		<li id="scocial">Visit us on <a href="#">facebook</a></li>
	</ul>

gristmill/templates/includes/tool_menu.html
<ul id="toolsMenu">
    <li><a href="#">Gift card recharge</a></li>
</ul>

gristmill/templates/includes/xx_latest_news_list.html
   <h2>Latest news</h2>
    <ul>
        {% for entry in entry_list %}
            <li><h6>{{ entry.headline }} - <em class="date">{{ entry.pub_date }}</em></h6>
				<p>{{ entry.body_text|truncatewords:5 }}</p>
			</li>
		{% empty %}
			<p>Sorry, no news found!!!</p>
        {% endfor %}
			   <li><a href="/blog/daily-grist/">More news</a></li>

    </ul>

gristmill/templates/includes/xx_mini_gal_list.html
<h3>Recent Gristmill Magic</h3>
	<ul style="list-style: none;">
    {% for image in image_list %}
		{# Each "image" is an Image model object. #}
        <li style="float: left; margin: 2px 1px 2px 0; padding: 2px; text-align: center;">
			<img style="height: 50px;" src="{{ image.filename.url }}" title="{{ image.caption }}" alt="{{ image.caption }}"/>
		</li>
	{% empty %}
	    <p>Sorry, no images found!!!</p>
    {% endfor %}
		<li style="float: left; margin: 2px; padding: 2px; text-align: center;"><a href="/gallery/all/">More photos</a></li>
    </ul>